admin:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

products:
    path:     /products
    defaults: { _controller: AdminBundle:Default:index }

categories:
    path:     /categories
    defaults: { _controller: AdminBundle:Default:listCategories }

categories-edit:
    path:     /categories/remove/{id}
    defaults: { _controller: AdminBundle:Default:removeCategory }
    requirements:
            id: '\d+'
categories-remove:
    path:     /categories/remove/{id}
    defaults: { _controller: AdminBundle:Default:removeCategory }
    requirements:
            id: '\d+'

users:
    path:     /users
    defaults: { _controller: AdminBundle:Default:index }

orders:
    path:     /orders
    defaults: { _controller: AdminBundle:Default:index }

messages:
    path:     /messages
    defaults: { _controller: AdminBundle:Default:index }
